### PR TITLE
Fix pip version number

### LINKED ISSUE #12: BUG: Wrong version set in pip
In https://github.com/conda-forge/autoawq-feedstock/pull/7, we're running into
```
import: 'awq'
+ pip check
pytablewriter 1.2.0 has requirement tcolorpy<1,>=0.0.5, but you have tcolorpy 0.0.0.
```

In other words, from the POV of `pip`, tcolorpy as packaged by conda-forge has version `0.0.0`.

CC @conda-forge/tcolorpy

### PR DESCRIPTION
**Pull request by yut23**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Fixes #12.

Also adds a test to check the version at build time.
See https://conda.discourse.group/t/package-version-shown-as-0-0-0-with-dynamic-versioning-in-pyproject-toml/615/2 for  more details.

### CODE REVIEW

**Comment by yut23** [comment]
@conda-forge-admin, please rerender

**Comment by yut23** [comment]
The more detailed setuptools_scm version requirements shouldn't be needed here, since setuptools-scm>=8 on conda-forge depends on python>=3.8.

**Comment by h-vetinari** [comment]
Just saw this PR, thanks a lot! Will fix it up and get it done. Would you be willing to join as a maintainer here?

CC @hadim, you're equally welcome. ;-)

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Review by h-vetinari — APPROVED** [review]

**Pull request merged**
